const SuggestedInvestigations = [
    "COMPLETE BLOOD PICTURE",
    "RANDOM BLOOD SUGAR",
    "SERUM URIC ACID",
    "SERUM VITAMIN D LEVELS",
    "SERUM VITAMIN B 12 LEVELS",
    "SERUM TSH",
    "CRP",
    "ESR",
    "RA FACTOR",
    "SERUM PTH LEVELS",
    "T3 T4 TSH",
    "FREE T3 FREE T4 LEVELS",
    "SERUM CALCIUM",
    "SERUM MAGNESIUM",
    "LIVER FUNCTION TEST",
    "VENUS COLOUR DOPPLER LOWER LIMB",
    "ARTERIAL COLOUR DOPPLER LOWER LIMB",
    "ULTRASOUND ABDOMEN WITH PELVIS",
    "COMPLETE URINE EXAMINATION",
    "WOUND SWAB FOR CULTURE AND SENSITIVITY"
];

export default SuggestedInvestigations;