
const SuggestedPhysiotherapy = [
    "AVOID SQUATTING",
    "AVOID STAIR CLIMBING",
    "AVOID CROSS LEGGED SITTING",
    "AVOID BENDING FORWARDS",
    "AVOID LIFTING WEIGHTS",
    "UNDERWATER EXERCISES",
    "ANKLE TOE MOVEMENTS",
    "STATIC QUADRICEPS EXERCISES",
    "STATIC CYCLING",
    "SWIMMING",
    "BEDSIDE KNEE ROM",
    "QUADRICEPS STRENGTHENING EXERCISES",
    "HAMSTRING STRENGTHENING EXERCISES",
    "VMO STRENGTHENING EXERCISES",
    "UNIVERSAL SHOULDER EXERCISES",
    "AVOID OVERHEAD ACTIVITY",
    "GALVANIC STIMULATION QUADRICEPS",
    "GALVANIC STIMULATION ROTATOR CUFF",
    "GALVANIC STIMULATION DELTOID",
    "SPINAL EXTENSION EXERCISES",
    "SPINAL FLEXION EXERCISES",
    "ACTIVE ELBOW ROM",
    "ACTIVE WRIST ROM",
    "ACTIVE FINGER MOVEMENTS"
]

export default SuggestedPhysiotherapy;
