const TabletInfo = [
  {
    value: "TAB.BAKWELL AP",
    label: "TAB.BAKWELL AP",
    foodRelation: [2, 4],
    timing: 2,
  },
  {
    value: "TAB.THIOWELL",
    label: "TAB.THIOWELL",
    foodRelation: [2, 4],
    timing: 2,
  },
  {
    value: "TAB.GLENROL DT",
    label: "TAB.GLENROL DT",
    foodRelation: [2, 4],
    timing: 2,
  },
  {
    value: "TAB.KETOROL DT",
    label: "TAB.KETOROL DT",
    foodRelation: [2, 4],
    timing: 2,
  },
  {
    value: "TAB.SEPIT MR",
    foodRelation: [2, 4],
    label: "TAB.SEPIT MR",
    timing: 2,
  },
  {
    value: "TAB.SETOLAC MR",
    foodRelation: [2, 4],
    label: "TAB.SETOLAC MR",
    timing: 2,
  },
  {
    value: "TAB.FLAMINATE",
    foodRelation: [2, 4],
    label: "TAB.FLAMINATE",
    timing: 2,
  },
  {
    value: "TAB.PIROWELL",
    foodRelation: [2, 4],
    label: "TAB.PIROWELL",
    timing: 2,
  },
  {
    value: "TAB.FLAMINATE SP",
    foodRelation: [2, 4],
    label: "TAB.FLAMINATE SP",
    timing: 2,
  },
  {
    value: "CAP.RAAP DSR",
    foodRelation: [1],
    label: "CAP.RAAP DSR",
    timing: 1,
  },
  {
    value: "CAP.RQD",
    foodRelation: [1],
    label: "CAP.RQD",
    timing: 1,
  },
  {
    value: "TAB.BOROFLEX",
    foodRelation: [4],
    label: "TAB.BOROFLEX",
    timing: 1,
  },
  {
    value: "TAB.QXOLE",
    foodRelation: [1],
    label: "TAB.QXOLE",
    timing: 1,
  },
  {
    value: "TAB.ORCERIN C2",
    foodRelation: [4],
    label: "TAB.ORCERIN C2",
    timing: 1,
  },
  {
    value: "JOINT PLUS SACHET",
    foodRelation: [4],
    label: "JOINT PLUS SACHET",
    timing: 1,
  },
  {
    value: "TAB.JOINT PLUS",
    foodRelation: [2, 6],
    label: "TAB.JOINT PLUS",
    timing: 2,
  },
  {
    value: "TAB.ALTRAJOINT C2",
    foodRelation: [2, 6],
    label: "TAB.ALTRAJOINT C2",
    timing: 2,
  },
  {
    value: "CAP.ROSIFIT TRIO",
    foodRelation: [2, 6],
    label: "CAP.ROSIFIT TRIO",
    timing: 2,
  },
  {
    value: "TAB.MYOTOP 150 MG",
    foodRelation: [2, 6],
    label: "TAB.MYOTOP 150 MG",
    timing: 2,
  },
  {
    value: "TAB.NUSON 150 MG",
    foodRelation: [2, 6],
    label: "TAB.NUSON 150 MG",
    timing: 2,
  },
  {
    value: "TAB.AXOVIT",
    foodRelation: [4],
    label: "TAB.AXOVIT",
    timing: 1,
  },
  {
    value: "TAB.ZINCOBION PLUS",
    foodRelation: [4],
    label: "TAB.ZINCOBION PLUS",
    timing: 1,
  },
  {
    value: "CAP.ENHANCE",
    foodRelation: [4],
    label: "CAP.ENHANCE",
    timing: 1,
  },
  {
    value: "TAB.CALBONA K2",
    foodRelation: [3],
    label: "TAB.CALBONA K2",
    timing: 1,
  },
  {
    value: "TAB.MEGACEE",
    foodRelation: [4],
    label: "TAB.MEGACEE",
    timing: 1,
  },
  {
    value: "TAB.OSTEOBION K2",
    foodRelation: [4],
    label: "TAB.OSTEOBION K2",
    timing: 1,
  },
  {
    value: "TAB.CLABONA XT",
    foodRelation: [3],
    label: "TAB.CLABONA XT",
    timing: 1,
  },
  {
    value: "CAP.CISSMORE",
    foodRelation: [2, 6],
    label: "CAP.CISSMORE",
    timing: 2,
  },
  {
    value: "TAB.CEFZUM",
    foodRelation: [2, 6],
    label: "TAB.CEFZUM",
    timing: 2,
  },
  {
    value: "CAP.QURECLAV 625",
    foodRelation: [2, 6],
    label: "CAP.QURECLAV 625",
    timing: 2,
  },
  {
    value: "TAB.FABUXA 80 MG",
    foodRelation: [4],
    label: "TAB.FABUXA 80 MG",
    timing: 1,
  },
  {
    value: "TAB.FOLAX G",
    foodRelation: [6],
    label: "TAB.FOLAX G",
    timing: 1,
  },
];

export default TabletInfo;
